"""
src/utils/mappings.py
Dictionnaires pour la standardisation des noms d'équipes entre différentes sources.
Le projet base ses noms officiels sur 'football-data.co.uk' (table `teams`).
"""

# Mapping : "Nom Understat" -> "Nom DB (Football-Data)"
UNDERSTAT_TO_FD = {
    # == Ligue 1 ==
    "Paris Saint Germain": "Paris SG",
    "Olympique Marseille": "Marseille",
    "Olympique Lyonnais": "Lyon",
    "Lille": "Lille",
    "Monaco": "Monaco",
    "Rennes": "Rennes",
    "Brest": "Brest",
    "Lens": "Lens",
    "Nantes": "Nantes",
    "Montpellier": "Montpellier",
    "Toulouse": "Toulouse",
    "Lorient": "Lorient",
    "Metz": "Metz",
    "Le Havre": "Le Havre",
    "Reims": "Reims",
    "Nice": "Nice",
    "Strasbourg": "Strasbourg",
    "Clermont Foot": "Clermont",
    "Saint-Etienne": "St Etienne",
    "Auxerre": "Auxerre",
    "Angers": "Angers",
    "Troyes": "Troyes",
    "Bordeaux": "Bordeaux",
    "Dijon": "Dijon",
    "Caen": "Caen",
    "Guingamp": "Guingamp",
    "Amiens": "Amiens",
    "Nimes": "Nimes",
    "Nancy": "Nancy",
    "Bastia": "Bastia",
    "Sochaux": "Sochaux",
    "Valenciennes": "Valenciennes",
    "Ajaccio": "Ajaccio",
    "Ajaccio GFCO": "Ajaccio GFCO",
    "Evian Thonon Gaillard": "Evian Thonon Gaillard",

    # == Premier League ==
    "Manchester United": "Man United",
    "Manchester City": "Man City",
    "Tottenham": "Tottenham",
    "Arsenal": "Arsenal",
    "Chelsea": "Chelsea",
    "Liverpool": "Liverpool",
    "Newcastle United": "Newcastle",
    "Wolverhampton Wanderers": "Wolves",
    "Nottingham Forest": "Nott'm Forest",
    "Aston Villa": "Aston Villa",
    "West Ham": "West Ham",
    "Crystal Palace": "Crystal Palace",
    "Brighton": "Brighton",
    "Bournemouth": "Bournemouth",
    "Fulham": "Fulham",
    "Everton": "Everton",
    "Brentford": "Brentford",
    "Sheffield United": "Sheffield United",
    "Luton": "Luton",
    "Burnley": "Burnley",
    "Leicester": "Leicester",
    "Southampton": "Southampton",
    "Leeds": "Leeds",
    "Ipswich": "Ipswich",
    "Queens Park Rangers": "QPR",
    "West Bromwich Albion": "West Brom",
    "Watford": "Watford",
    "Stoke City": "Stoke",
    "Sunderland": "Sunderland",
    "Hull City": "Hull",
    "Swansea": "Swansea",
    "Norwich": "Norwich",
    "Cardiff": "Cardiff",
    "Middlesbrough": "Middlesbrough",
    "Wigan Athletic": "Wigan",
    "Reading": "Reading",
    "Blackburn Rovers": "Blackburn",
    "Bolton": "Bolton",
    "Blackpool": "Blackpool",
    "Birmingham": "Birmingham",
    "Huddersfield": "Huddersfield",
}

# Mapping : "Nom ESPN API" -> "Nom DB (Football-Data)"
ESPN_TO_FD: dict[str, str] = {
    # == Ligue 1 ==
    "Stade Rennais": "Rennes",
    "Stade Rennais FC": "Rennes",
    "Le Havre AC": "Le Havre",
    "AJ Auxerre": "Auxerre",
    "AS Monaco": "Monaco",
    "RC Lens": "Lens",
    "RC Strasbourg": "Strasbourg",
    "Strasbourg Alsace": "Strasbourg",
    "LOSC Lille": "Lille",
    "LOSC": "Lille",
    "OGC Nice": "Nice",
    "Olympique Lyonnais": "Lyon",
    "Olympique de Marseille": "Marseille",
    "Olympique Marseille": "Marseille",
    "Paris Saint-Germain": "Paris SG",
    "Paris Saint Germain": "Paris SG",
    "PSG": "Paris SG",
    "FC Nantes": "Nantes",
    "Stade Brestois": "Brest",
    "Stade Brestois 29": "Brest",
    "Montpellier HSC": "Montpellier",
    "Toulouse FC": "Toulouse",
    "Stade de Reims": "Reims",
    "Clermont Foot": "Clermont",
    "Clermont Foot 63": "Clermont",
    "AS Saint-Étienne": "St Etienne",
    "AS Saint-Etienne": "St Etienne",
    "Saint-Étienne": "St Etienne",
    "Saint-Etienne": "St Etienne",
    "FC Lorient": "Lorient",
    "FC Metz": "Metz",
    "SCO Angers": "Angers",
    "Angers SCO": "Angers",
    # == Premier League ==
    "Manchester United": "Man United",
    "Manchester City": "Man City",
    "Newcastle United": "Newcastle",
    "Wolverhampton Wanderers": "Wolves",
    "Wolverhampton": "Wolves",
    "Wolverhampton Wanderers FC": "Wolves",
    "Nottingham Forest": "Nott'm Forest",
    "Sheffield United": "Sheffield United",
    "West Ham United": "West Ham",
    "AFC Bournemouth": "Bournemouth",
    "Leicester City": "Leicester",
    "Ipswich Town": "Ipswich",
    "Luton Town": "Luton",
}


def get_fd_name(understat_name: str) -> str:
    """Retourne le nom officiel (DB) ou le nom original si non mappé."""
    return UNDERSTAT_TO_FD.get(understat_name, understat_name)


def get_fd_name_espn(espn_name: str) -> str:
    """Retourne le nom officiel (DB) depuis un nom ESPN, ou le nom original si non mappé."""
    return ESPN_TO_FD.get(espn_name, espn_name)
